// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"

	"github.com/google/uuid"
)

type Character struct {
	ID        uuid.UUID
	GameID    uuid.UUID
	Main      sql.NullString
	Body      sql.NullString
	Health    sql.NullString
	Job       sql.NullString
	Hobby     sql.NullString
	Phobia    sql.NullString
	Inventory sql.NullString
	Info      sql.NullString
	Ability   sql.NullString
}

type Game struct {
	ID         uuid.UUID
	Apocalypse sql.NullString
	Size       sql.NullInt32
	Time       sql.NullInt32
	Food       sql.NullInt32
	Place      sql.NullString
	Rooms      sql.NullString
	Resources  sql.NullString
}
